export enum PLIST_ACTIONS {
    GET_PLIST = "GET_PLIST",
    ADD_PLIST = "ADD_PLIST",
    DELETE_PLIST = "DELETE_PLIST",
    UPDATE_PLIST = "UPDATE_PLIST",
    ADD_SONG_TO_PLIST = "ADD_SONG_TO_PLIST",
    DELETE_SONG_FROM_PLIST = "DELETE_SONG_FROM_PLIST"
}